# Changes here will be overwritten by Copier
_commit: e730ed7
_src_path: gh:audivir/copier-template
description: Cross-platform zsh dotfiles and package-manager bootstrap scripts
github_org: audivir
project_name: zshsetup
project_slug: zshsetup
project_type: shell
publishable: false
