# GCC's libstdc++ and libgcc_s for musl hosts without them, e.g. for bun and Rust
platforms = ["musl_x64", "musl_arm64"]
deps = ["patchelf"]
content = true
keep = ["usr/lib/libstdc++.so.6*", "usr/lib/libgcc_s.so.1"]
check = { libs = ["libstdc++.so.6", "libgcc_s.so.1"] }
# musl looks up the dependencies of a library in the RUNPATH of that library
post_install = """patchelf --set-rpath '$ORIGIN' "$PREFIX"/dir/usr/lib/libstdc++.so.6.*"""

[external]
apk = "libstdc++"

[release]
type = "apk"
package = "libstdc++"

[download]
type = "apk"
packages = ["libstdc++", "libgcc"]
