# the static musl build runs on all Linux hosts, the glibc one crashes on older glibc
bin = { curl = "curl" }

[external]
apt = "curl"
apk = "curl"

[release]
type = "github"
repo = "stunnel/static-curl"

[download]
type = "github"

[assets]
glibc_x64 = "curl-linux-x86_64-musl-{{ tag }}.tar.xz"
glibc_arm64 = "curl-linux-aarch64-musl-{{ tag }}.tar.xz"
musl_x64 = "curl-linux-x86_64-musl-{{ tag }}.tar.xz"
musl_arm64 = "curl-linux-aarch64-musl-{{ tag }}.tar.xz"
macos_arm64 = "curl-macos-arm64-{{ tag }}.tar.xz"
