# git finds libexec and share relative to the real path of its binary, so the whole archive is the
# package dir and bin gets symlinks
content = true
links.git = "{{ dir }}/bin/git"
links.git-receive-pack = "{{ dir }}/bin/git-receive-pack"
links.git-upload-archive = "{{ dir }}/bin/git-upload-archive"
links.git-upload-pack = "{{ dir }}/bin/git-upload-pack"
completions.git = { bash = "share/bash-completion/completions/git" }
check = {}

[external]
brew = "git"
apt = "git"
apk = "git"

[release]
type = "github"
repo = "audivir/git-static"

[download]
type = "github"

[assets]
glibc_x64 = "git-static-linux-amd64.tar.gz"
glibc_arm64 = "git-static-linux-arm64.tar.gz"
musl_x64 = "git-static-linux-musl-amd64.tar.gz"
musl_arm64 = "git-static-linux-musl-arm64.tar.gz"
macos_arm64 = "git-static-macos-arm64.tar.gz"
