bin = { jq = "{{ asset }}" }

check = {}

[external]
brew = "jq"
apt = "jq"
apk = "jq"

[release]
type = "github"
repo = "jqlang/jq"

[download]
type = "github"

[assets]
glibc_x64 = "jq-linux-amd64"
glibc_arm64 = "jq-linux-arm64"
musl_x64 = "jq-linux-amd64"
musl_arm64 = "jq-linux-arm64"
macos_arm64 = "jq-macos-arm64"
