#:schema https://raw.githubusercontent.com/audivir/pmg/main/schema.json
# uvc has no releases, so the tag is the start of the sha256 of the current script
deps = ["curl", "uv"]
bin = { uvc = "{{ asset }}" }
check = { cmd = ["uvc", "envs"] }

test = "{{ cmd }} envs"
[external]
brew = "uvc"

[release]
type = "command"
cmd = '''
curl -fsSL https://github.com/audivir/uvc/raw/refs/heads/main/uvc |
  uv run --no-project --quiet python -c \
    'import hashlib, sys; print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest()[:12])'
'''

[download]
type = "url"
url = "https://github.com/audivir/uvc/raw/refs/heads/main/{{ asset }}"

[assets]
glibc_x64 = "uvc"
glibc_arm64 = "uvc"
musl_x64 = "uvc"
musl_arm64 = "uvc"
macos_arm64 = "uvc"
